name: submit_tool

on:
  pull_request_target:
    types: [opened, reopened, edited, review_requested]
    paths:
    - 'tools/**.md'

env:
  id: '1LQKMaOQlC_flskr2-9Src7RFtMRPrICCk20qYX8X2OY'
  remote: 'agnescameron/HelioKNOW'
  branch: main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check proposed additions are valid
    steps:

      - name: get PR branch
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Fetch
        run: |
          git fetch origin pull/${{ github.event.number }}/head:${{ env.BRANCH_NAME }}
          git checkout ${{ env.BRANCH_NAME }}

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Set up Python environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install python-frontmatter
          python3 -m pip install -v gspread==4.0.1
          python3 -m pip install gspread_dataframe
          python3 -m pip install pandas
          python3 -m pip install six
          python3 -m pip install Pillow

      - id: 'read_files'
        uses: Ana06/get-changed-files@v2.0.0

      - name: test changed files are valid
        id: run_test
        run: |
          git status
          for new_file in ${{ steps.read_files.outputs.added_modified }}; do
            if [ "${new_file: -3}" == ".md" ]
            then
              echo "testing validity of ${new_file}"
              echo ::set-output name=test_error::$(python3 scripts/tests/check_frontmatter.py ${new_file})
            fi
          done

      - name: return errors
        if: false==(steps.run_test.outputs.test_error == '[]')
        run: |
            echo ${{ steps.run_test.outputs.test_error }}

      - name: Create comment
        if: false==(steps.run_test.outputs.test_error == '[]')
        uses: jungwinter/comment@v1
        with:
          type: create
          body: "integration of submitted file(s) failed with errors ${{ steps.run_test.outputs.test_error }}. \
            Please check your files and try again. In order to re-submit the files, please request \
            a pull request review. GitHub provides a guide to doing so \
            [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review)"
          issue_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: exit on failure
        if: false==(steps.run_test.outputs.test_error == '[]')
        run: exit 1

      - name: report success
        run: |
            echo "no errors found in submitted files, will now run integration script"

      - name: iterate over pull request files
        id: changed_files
        env:
          INPUT_SHEET_ID: '1bdyhGrj0oNz-_qW3Rv2GNGqhZZ73rgj-DYWePLA_1Ms'
          INPUT_SHEET_TITLE: 'HelioKNOW_tools'
          INPUT_CREDS: ${{ secrets.GSHEET_CREDENTIALS }}
          INPUT_TEMPDIR: 'index_archive'
        run: |
          git status
          for added_file in ${{ steps.read_files.outputs.added }}; do
            if [ "${added_file: -3}" == ".md" ]
            then
              echo "this is a markdown file ${added_file}"
              python3 scripts/submit_dataset.py ${added_file}
              echo "::set-output name=commit_files::true"
            fi
          done
          for modified_file in ${{ steps.read_files.outputs.modified }}; do
            if [ "${modified_file: -3}" == ".md" ]
            then
              echo "this is a markdown file ${modified_file}"
              python3 scripts/edit_dataset.py ${modified_file}
            fi
          done

      - name: Commit files
        if: steps.changed_files.outputs.commit_files == 'true'
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add index_archive/*.csv tools/*.md app/assets/thumbnails
            git commit -m "added uuid to file, updated CSV (#${{ github.event.number }})"

      - name: Push to new branch
        run: |
            git push --set-upstream origin ${{ env.BRANCH_NAME }}

      - name: Checkout to main branch
        uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Commit merge
        run: |
            git fetch
            git config pull.rebase false
            git pull origin ${{ env.BRANCH_NAME }}
            git pull
            git push
